### PR TITLE
Separate out integration/view into a separate repo (hdf,panda,csv)

### LINKED ISSUE #122: Separate out integration/view into a separate repo (hdf,panda,csv)

### PR DESCRIPTION
**Pull request by vchendrix**
Separate out integration/view into a separate repo (hdf,panda,csv)
+ Removes basin3d.synthese.get_timeseries_data and all related
  tests, functions and classes.
+ Updates yaml load for credentials with loader options
+ Adds tests to bring code coverage back up to 92%
+ Removes all documentation associated get_timeseries_data call

Simplifies installing development dependencies
+ Updates CONTRIBUTING.md to reflect the new mode of
  setting up the environment for development
+ Updates Github Actions

NOTE: removed code will be in a new repository called
BASIN-3D/basin3d-views.

Closes #122 

## Type of change

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested?

- [X] Unit tests
- [X] Integration tests 
- [X] Test coverage >= 92%
- [X] Flake8 Tests 
- [X] Mypy Tests 

### Test Configuration
* Python Version: 3.8.5

## PR Self Evaluation
strikethrough things that don’t make sense for your PR

- [x] My code follows the agreed upon best practices
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests or modified existing tests that prove my fix is effective or that my feature works
- [x] Existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in the appropriate modules
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by dschristianson — COMMENTED** [review]
Code looks great generally. Thank you!

I'm not having success with the new instructions for dev setup, using Python 3.8 for the conda environment. Probably most efficient to chat with you about this unless there is something about the python version I am missing.

**Comment by vchendrix** [comment]
> Code looks great generally. Thank you!
> 
> I'm not having success with the new instructions for dev setup, using Python 3.8 for the conda environment. Probably most efficient to chat with you about this unless there is something about the python version I am missing.

Thanks for the feedback. I will take a quick look at what I wrote to see if it is obvious to me what the problem is.

**Comment by vchendrix** [comment]
@dschristianson I made a slight change to the setup instructions.  You will need to remove your conda environment and try again

```
conda deactivate basin3d
conda remove -n basin3d --all
```
Then follow the setup instructions.  Thanks!

**Review by dschristianson — APPROVED** [review]
Looks great, @vchendrix. Thanks for fix to setting up dev environment.
Minor comment -- up to you for addressing. Am approving so you can merge.

**Pull request merged**
