### PR TITLE
Add missing h5py module to docs/requirements.py

### LINKED ISSUE #101: ReadTheDocs Quick Guide not rendering properly
**Describe the bug**
ReadTheDocs: Quick Guide not picking up the autofunction references to synthesis.py

**To Reproduce**
See https://basin3d.readthedocs.io/en/develop/quick_guide.html

**Expected behavior**
Embedded documentation in synthesis.py should populate the Quick Guide

### PR DESCRIPTION
**Pull request by dschristianson**
Closes #101

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- [x] Unit tests
- [ ] Integration tests 
- [ ] Test coverage >= 90%
- [x] Flake8 Tests 
- [x] Mypy Tests 
- [ ] Other - generated ReadTheDocs: https://basin3d.readthedocs.io/en/issue-101/quick_guide.html

### Test Configuration
* Python Version: 3.7.11

## PR Self Evaluation
- [x] My code follows the agreed upon best practices
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
- [x] My changes generate no new warnings
~- [ ] I have added tests or modified existing tests that prove my fix is effective or that my feature works~
- [x] Existing unit tests pass locally with my changes
~- [ ] Any dependent changes have been merged and published in the appropriate modules~
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by dschristianson** [comment]
Once this PR has been merged, the issue-101 branch on ReadTheDocs should be made inactive. Thx.

**Review by vchendrix — COMMENTED** [review]
@dschristianson Is there a reason that this goes in this docs/requirements.txt and not the requirements.txt for the basin3d?  Does readthedocs not load the requirements from the main requirements?

**Comment by dschristianson** [comment]
@vchendrix: Inspecting the log for the ReadTheDocs build, it looks like only docs/requirements.txt is installed. I did not look into why or if/how this could be changed.

**Comment by vchendrix** [comment]
I think that if we require h5py to generate the documentation, it should
probably be in our main requirements.txt.  Alos, how is h5py referenced in
the code that is auto documented? Is there a reason that tinydb is not
required?
+++++++++++++++++++++++++++++++++
Val Hendrix
***@***.***
Lawrence Berkeley National Lab

Mail Stop: 50B-2239
Room:      50B-2258E
Phone:     (510) 495-2905
Pronouns: she/hers
+++++++++++++++++++++++++++++++++

**Comment by dschristianson** [comment]
@vchendrix: h5py is in the main requirements file. The ReadTheDocs issue occurs when the basin3d/synthesis.py module is imported because the documentation uses the autofunction that points to this module (see error messages in the issue ticket). tinydb is not imported in the synthesis module so it is not required for the documentation.

**Comment by vchendrix** [comment]
Got it. Thanks! I was looking at the wrong branch

**Pull request merged**
